### ISSUE TITLE
custom configuration parser blows up when configuration values contain nested key/val pairs

### ISSUE THREAD

**Issue by jamesbeedy** [charmed-hpc/slurm-charms#14]
### Bug Description

Custom configuration parser doesn't account for nested `k=v` type configuration.

### To Reproduce

deploy the slurm charms and set `juju config slurmctld slurm-conf-parameters='JobAcctGatherFrequency="task=1"'`

### Environment

slurm charms deployed from edge

### Relevant log output

```shell
na
```

**Comment by NucciTheBoss** [comment]
Hi @jamesbeedy -

Thank you for this report! We should be able to address this relatively easily. Code in `slurmutils` is capable of handling this syntax.

**Comment by jamesbeedy** [comment]
> Hi @jamesbeedy -
> 
> Thank you for this report! We should be able to address this relatively easily. Code in `slurmutils` is capable of handling this syntax.

I've always been +1 for `slurmutils`, but I didn't think it could initialize a config object from from a python dict, which was what I thought was blocking us initially ... if I recall correctly

**Comment by NucciTheBoss** [comment]
> I've always been +1 for `slurmutils`, but I didn't think it could initialize a config object from from a python dict, which was what I thought was blocking us initially ... if I recall correctly

I have good news for you then. Guess what we're planning on doing this week :smile:
