### ISSUE TITLE
slurmctld charm should configure a sane value for the `TaskPlugin` slurm configuration parameter

### ISSUE THREAD

**Issue by jamesbeedy** [charmed-hpc/slurm-charms#16]
### Bug Description

The `TaskPlugin` configuration is not handled by the charms and requires a custom user-supplied configuration to configure. 

### To Reproduce

na

### Environment

na

### Relevant log output

```shell
na
```

### Additional context

The `TaskPlugin` is a configuration parameter we set as custom user supplied config for each deployment.

The slurm charms could configure `TaskPlugin=task/cgroup,task/affinity` if `is_container()` is `False` and `TaskPlugin=task/affinity` otherwise to provide a sane default value that corresponds with the`ProctrackType` configuration.

**Comment by NucciTheBoss** [comment]
@jamesbeedy question - does `task/cgroup` require us to ensure the hybrid cgroups are disabled on the nodes?

**Comment by jamesbeedy** [comment]
> @jamesbeedy question - does `task/cgroup` require us to ensure the hybrid cgroups are disabled on the nodes?

no
