### ISSUE TITLE
use sane defaults for `cgroup.conf`

### ISSUE THREAD

**Issue by jamesbeedy** [charmed-hpc/slurm-charms#31]
### Bug Description

The current cgroup.conf defaults provided by slurmctld charm are outdated and deprecated. 

### To Reproduce

main

### Environment

main

### Relevant log output

```shell
main
```

**Comment by NucciTheBoss** [comment]
For additional context, `CgroupAutomount` is no longer a valid option for _cgroup.conf_, so (a) this will likely cause Slurm to be unhappy when it reads the _cgroup.conf_ file and (b) there are other documented defaults that we should use.

`CgroupAutomount` also mentioned anywhere in the [_cgroup.conf_ man page](https://manpages.ubuntu.com/manpages/oracular/en/man5/cgroup.conf.5.html#description).
